<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xht.platform</groupId>
        <artifactId>xht-platform</artifactId>
        <version>1.0.0</version>
    </parent>

    <name>xht-admin</name>
    <artifactId>xht-admin</artifactId>
    <packaging>pom</packaging>
    <description>xht-admin 后台管理模块</description>

    <modules>
        <module>xht-admin-adapter</module>
        <module>xht-admin-common</module>
        <module>xht-admin-domain</module>
        <module>xht-admin-infrastructure</module>
        <module>xht-admin-start</module>
    </modules>
    
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.xht.platform</groupId>
                <artifactId>xht-admin-common</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.xht.platform</groupId>
                <artifactId>xht-admin-domain</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.xht.platform</groupId>
                <artifactId>xht-admin-infrastructure</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.xht.platform</groupId>
                <artifactId>xht-admin-adapter</artifactId>
                <version>1.0.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <finalName>${project.artifactId}</finalName>
    </build>
</project>