<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xht.framework</groupId>
        <artifactId>xht-framework-parent</artifactId>
        <version>1.0.0</version>
        <relativePath>./xht-framework-parent/pom.xml</relativePath>
    </parent>
    <groupId>com.xht.platform</groupId>
    <artifactId>xht-platform</artifactId>
    <packaging>pom</packaging>
    <name>xht-platform</name>
    <description>xht-platform</description>
    <version>1.0.0</version>

    <modules>
        <module>xht-admin</module>
        <module>xht-framework-parent</module>
        <module>xht-auth</module>
        <module>xht-gateway</module>
        <module>xht-generate</module>
        <module>xht-platform-common</module>
        <module>xht-platform-client</module>
        <module>xht-workflow</module>
    </modules>

    <properties>
        <revision>1.0.0</revision>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven-compiler-plugin.version>3.14.0</maven-compiler-plugin.version>
        <spring-boot.version>3.5.14</spring-boot.version>
        <spring-cloud.version>2025.0.1</spring-cloud.version>
        <spring-cloud-alibaba.version>2025.0.0.0</spring-cloud-alibaba.version>
        <lombok.version>1.18.36</lombok.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
    </properties>

    <!-- 依赖管理，集中定义依赖版本 -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.xht.platform</groupId>
                <artifactId>xht-admin-common</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.xht.platform</groupId>
                <artifactId>xht-generate-common</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.xht.platform</groupId>
                <artifactId>xht-workflow-common</artifactId>
                <version>1.0.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <!-- 项目具体依赖 -->
    <dependencies>
        <!--测试依赖-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <!-- 构建配置 -->
    <build>
        <plugins>
            <!-- Maven 资源插件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
            </plugin>
            <!-- Maven 编译插件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
    <!--定义不同的构建配置文件-->
    <profiles>
        <!--开发环境-->
        <profile>
            <id>dev</id>
            <properties>
                <profiles.active>dev</profiles.active>
                <log.file.path>D:\xht-logs</log.file.path>
                <!-- nacos相关配置 -->
                <nacos.username>nacos</nacos.username>
                <nacos.password>nacos</nacos.password>
                <nacos.discovery.address>192.168.100.1:8848</nacos.discovery.address>
                <nacos.config.address>192.168.100.1:8848</nacos.config.address>
                <nacos.namespace>xht-dev</nacos.namespace>
                <nacos.group>XHT_CLOUD_GROUP</nacos.group>
                <nacos.version>v3</nacos.version>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <!--测试环境-->
        <profile>
            <id>test</id>
            <properties>
                <profiles.active>test</profiles.active>
                <log.file.path>/home/xht-logs</log.file.path>
                <!-- nacos相关配置 -->
                <nacos.username>nacos</nacos.username>
                <nacos.password>nacos</nacos.password>
                <nacos.discovery.address>127.0.0.1:8848</nacos.discovery.address>
                <nacos.config.address>127.0.0.1:8848</nacos.config.address>
                <nacos.namespace>xht-test</nacos.namespace>
                <nacos.group>XHT_CLOUD_GROUP</nacos.group>
                <nacos.version>v3</nacos.version>
            </properties>
        </profile>
        <!--生产环境-->
        <profile>
            <id>prod</id>
            <properties>
                <profiles.active>prod</profiles.active>
                <log.file.path>/home/xht-logs</log.file.path>
                <!-- nacos相关配置 -->
                <nacos.username>nacos</nacos.username>
                <nacos.password>nacos</nacos.password>
                <nacos.discovery.address>127.0.0.1:8848</nacos.discovery.address>
                <nacos.config.address>127.0.0.1:8848</nacos.config.address>
                <nacos.namespace>xht-prod</nacos.namespace>
                <nacos.group>XHT_CLOUD_GROUP</nacos.group>
                <nacos.version>v3</nacos.version>
            </properties>
        </profile>
    </profiles>
</project>
