<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xht.platform</groupId>
        <artifactId>xht-generate</artifactId>
        <version>1.0.0</version>
    </parent>

    <name>xht-generate-domain</name>
    <artifactId>xht-generate-domain</artifactId>
    <packaging>jar</packaging>
    <description>xht-generate-domain 代码生成器 domain 层</description>

    <dependencies>
        <!-- Swagger Core -->
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations-jakarta</artifactId>
        </dependency>
        <dependency>
            <groupId>com.xht.platform</groupId>
            <artifactId>xht-generate-common</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
    </build>
</project>