server:
  port: 1314

spring:
  application:
    name: xht-generate
  profiles:
    active: dev
  # 数据源配置
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/xht_platform?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: @nacos.discovery.address@
        username: @nacos.username@
        password: @nacos.password@
        namespace: @nacos.namespace@
        group: @nacos.group@
      config:
        server-addr: @nacos.config.address@
        username: @nacos.username@
        password: @nacos.password@
        namespace: @nacos.namespace@
        group: @nacos.group@
        file-extension: yml
        prefix: ${spring.application.name} # 默认配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  override-with-generic-response: false # 解决springdoc和knife4版本冲突问题
  default-flat-param-object: true # 解决参数列表显示问题
  paths-to-exclude:
    - /api/**
    - /error
    - /actuator/**
    - /favicon.ico
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDel
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*Mapper.xml