server:
  port: 1314

spring:
  application:
    name: xht-module-generate
  profiles:
    active: dev
  # 数据源配置
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
springdoc:
  api-docs:
    enabled: true
  override-with-generic-response: false # 解决springdoc和knife4版本冲突问题
  default-flat-param-object: true # 解决参数列表显示问题