<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xht.platform</groupId>
        <artifactId>xht-platform</artifactId>
        <version>1.0.0</version>
    </parent>

    <name>xht-workflow</name>
    <artifactId>xht-workflow</artifactId>
    <packaging>pom</packaging>
    <description>xht-workflow工作流模块</description>

    <modules>
        <module>xht-workflow-adapter</module>
        <module>xht-workflow-domain</module>
        <module>xht-workflow-infrastructure</module>
        <module>xht-workflow-start</module>
    </modules>

    <properties>
        <flowable.version>7.2.0</flowable.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.xht.platform</groupId>
                <artifactId>xht-workflow-domain</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.xht.platform</groupId>
                <artifactId>xht-workflow-infrastructure</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.xht.platform</groupId>
                <artifactId>xht-workflow-adapter</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.flowable</groupId>
                <artifactId>flowable-spring-boot-starter</artifactId>
                <version>${flowable.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <finalName>${project.artifactId}</finalName>
    </build>

</project>