server:
  port: 8180
spring:
  application:
    name: xht-demo
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          spring:
            client-id: oidc-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8180/login/oauth2/code/spring
            scope:
              - openid
        provider:
          spring:
            jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks
            # 授权端点（固定格式：授权服务器地址 + /oauth2/authorize）
            authorization-uri: http://127.0.0.1:9000/oauth2/authorize
            # 令牌获取端点（固定格式：授权服务器地址 + /oauth2/token）
            token-uri: http://127.0.0.1:9000/oauth2/token
            # 用户信息端点（获取登录用户信息，授权服务器默认接口）
            user-info-uri: http://127.0.0.1:9000/userinfo
            # 用户信息返回类型（固定）
            user-info-authentication-method: header

  data:
    redis:
      password:
      host: 127.0.0.1
      port: 6379
      database: 1
    mongodb:
      uri: mongodb://127.0.0.1:27017/moaZwfw
springdoc:
  api-docs:
    enabled: true
  override-with-generic-response: false # 解决springdoc和knife4版本冲突问题
xht:
  safety:
    xss:
      enable: true
  global:
    dict:
      unit: microseconds
      properties:
        timeout: 5000
        retry: 3
        retry-interval: 5000
  blog:
    repository-type: default