server:
  port: 10001
spring:
  application:
    name: xht-demo
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    enabled: true
  override-with-generic-response: false # 解决springdoc和knife4版本冲突问题
xht:
  safety:
    xss:
      enable: true