CREATE TABLE IF EXISTS `b_log`
(
    `id`           bigint NOT NULL COMMENT '主键ID',
    `trace_id`     varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT '链路追踪id',
    `title`        varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '日志名称',
    `service_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT '服务名称',
    `description`  varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '日志描述',
    `status`       varchar(32) COLLATE utf8mb4_unicode_ci                        DEFAULT '' COMMENT '日志状态（SUCCESS:成功;FAIL:失败）',
    `remote_addr`  varchar(128) COLLATE utf8mb4_unicode_ci                       DEFAULT '' COMMENT '操作IP地址',
    `user_agent`   varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户代理（浏览器/客户端信息）',
    `request_uri`  varchar(512) COLLATE utf8mb4_unicode_ci                       DEFAULT '' COMMENT '请求URI',
    `method`       varchar(16) COLLATE utf8mb4_unicode_ci                        DEFAULT '' COMMENT '请求方式（GET/POST/PUT/DELETE等）',
    `params`       json                                                          DEFAULT NULL COMMENT '操作提交的数据',
    `execute_time` datetime                                                      DEFAULT NULL COMMENT '执行开始时间',
    `timing`       varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  DEFAULT '0' COMMENT '执行时间(毫秒)',
    `exception`    text COLLATE utf8mb4_unicode_ci COMMENT '异常信息',
    `create_by`    varchar(64) COLLATE utf8mb4_unicode_ci                        DEFAULT '' COMMENT '创建人',
    `create_time`  datetime(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `update_by`    varchar(64) COLLATE utf8mb4_unicode_ci                        DEFAULT '' COMMENT '更新人',
    `update_time`  datetime(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY            `idx_sys_log_trace_id` (`trace_id`),
    KEY            `idx_sys_log_status` (`status`),
    KEY            `idx_sys_log_execute_time` (`execute_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统日志表';