<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xht.platform</groupId>
        <artifactId>xht-admin</artifactId>
        <version>1.0.0</version>
    </parent>

    <name>xht-admin-adapter</name>
    <artifactId>xht-admin-adapter</artifactId>
    <packaging>jar</packaging>
    <description>xht-admin-adapter 后台管理 adapter 层</description>


    <dependencies>
        <dependency>
            <groupId>com.xht.platform</groupId>
            <artifactId>xht-admin-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>com.xht.framework</groupId>
            <artifactId>xht-spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.xht.framework</groupId>
            <artifactId>xht-spring-boot-starter-resource-server</artifactId>
        </dependency>
        <dependency>
            <groupId>com.xht.framework</groupId>
            <artifactId>xht-spring-boot-starter-log</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
    </build>
</project>