server:
  port: 8080
  servlet:
    session:
      cookie:
        name: GATEWAY-CLIENT
spring:
  session:
    redis:
      flush-mode: on_save
      namespace: gateway:session
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          routes:
            - id: xht-auth
              uri: lb://xht-auth #此处需要使用lb协议
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: xht-module-admin
              uri: lb://xht-module-admin #此处需要使用lb协议
              predicates:
                - Path=/admin/**
              filters:
                - StripPrefix=1
                - TokenRelay
            - id: xht-module-generate
              uri: lb://xht-module-generate #此处需要使用lb协议
              predicates:
                - Path=/generate/**
              filters:
                - StripPrefix=1
          default-filters:
  data:
    redis:
      host: 192.168.100.1
      port: 6379
      timeout: 10000
      jedis:
        pool:
          enabled: true
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
      password:
      database: 0

xht:
  global:
    banner:
      enable: true
    app-name: 授权服务
    host-name: www.xht.sso.com
  security:
    ignore:
      whites:
        add-swagger-ignore-urls: true
    gateway:
      authenticated-urls:
        - /get/token
        - /authorized
      allowed-origins:
        - www.xht.com
      app-base-uri: http://www.xht.com:3000/oauth2
knife4j:
  gateway:
    enabled: true     # ① 第一个配置，开启gateway聚合组件
    strategy: discover # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    discover:
      enabled: true   # ③ 第三行配置，开启discover模式
      version: openapi3 # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档